### ISSUE TITLE
Create necessary Cloud Foundry metadata files for deployment 

### ISSUE THREAD

**Issue by jr4998** [devopsorders/orders#47]
**As a** developer
**I need** to create the proper metadata files
**So that** IBM Cloud will know how to deploy your application

**Assumptions:** 
* Include manifest.yml, Procfile, runtime.txt files
* Use cf push to push application to IBM Cloud
* use gunicorn as production webserver

**Acceptance Criteria:**

When I run `bx cf push` from the command line of my VM
Then it returns successfully and I can access my app url in the cloud

**Comment by shooker** [comment]
- Example [manifest.yml](https://github.com/nyu-devops/lab-bluemix-cf/blob/master/manifest.yml) file
- Example [Procfile](https://github.com/nyu-devops/lab-bluemix-cf/blob/master/Procfile)
- Example [runtime.txt](https://github.com/nyu-devops/lab-bluemix-cf/blob/master/runtime.txt) file (Need to change to Python 3.6)

**Comment by shooker** [comment]
@mstefaniak10 I'm going to push the branch up as `feature/deploy` if you want to take a look. Once you accept my invite from Bluemix you should be able to run `ibmcloud login -a https://api.ng.bluemix.net --apikey @~/.bluemix/apiKey.json -o sebastian.hooker@stern.nyu.edu -s dev` from inside the VM and test the deployment. Leave the `sebastian.hooker@stern.nyu.edu` as is because it's technically the organization's name right now.

Also, you may need to merge in my CLI branch pull request and re-provision your VM before it works.

Current errors from recent logs:
`ERR No start command specified by buildpack or via Procfile.`
`ERR App will not start unless a command is provided at runtime.`
`ERR python: can't open file 'manage.py': [Errno 2] No such file or directory`
